apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-modules
  annotations:
    github.com/project-slug: sampgreenwell-cyber/terraform-modules
spec:
  type: other
  lifecycle: unknown
  owner: guests
